language: scala
scala:
   - 2.12.8
jdk:
  - oraclejdk8
env:
  global:
  - secure: M/f/K1H0pZS5rgeoQXroFJlz5t2l8UcP+Bogo2jn3drvrqdPB22Z0MzkorH9diBrtykGZmc3X0A8Y9SQob7YaJ+lD0XbSuwzM9TgAKHLg8CpJQffFpE0xUHybcrcdTnC19iiTI3vovr2nQzlYn31F0X0RXMSDyW0zOIDX9kDGuk=
  - secure: aEgUK6zpFDbDQNXVsJC9Y3CrvUTrbDci7U6mM/vR2/ksVL4dVMBCJAJsdXWwc12wIlYRNDrtuZ62/R+LbS8O1gjIeyU8hKhc81L8pfyJFOm9BztbN+4XqkPsXS7WqgpqI6lr1TABdHaHPwTCh5kFLtqkCD2NXMmi7uhmScJfVc0=
  - secure: LPO6f56t82laN2lzNuVuAIQkmkn8wOvmOzeu5ozYn9afJ+GGxjdJJ9TEYOQA5bZFKY/p6o65MemhlidhdMpZu++G1nVVdPoAh+NvEfesQxkQx0lFta6u2l2nKgUnpZL2mW8skM1LGepOyUZFujBAcSH6GHmQN0IP4zGVSrUvMX0=
  - secure: hDo2jt06gx02utmCMb548NEeTAtIgTg53SYL+rPydhryCZHzQISPHlHB/SDKATlalYU6nP+1zz9gANA1HVgN83BaAzI82CoBcsBvVSAw+MKYMDbdf3yoEpe0DJyzibscu57nb7rvi+Xswse93mib1wkdy4eOXB1L0YwKW6dlxB0=
  - secure: xtx+EvI6UKAndt1/9pay+YA+6QG8TylETGQemDMGENTp2er/u013CPTZRrJu7znRiQdPamI8hPsy1GRGKt7cCoyFIv5MWtMOodNVcxbhDbl7z3j5mcKIp2RJmv1XaL0nJnltnIJj0P0ohA4BVzpi9jthaj+WzI9O6OIKRyuIvdU=
script:
  - sbt ++$TRAVIS_SCALA_VERSION coverage test coverageReport
deploy:
  skip_cleanup: true
  provider: script
  script: ./.travis/deploy.sh $TRAVIS_TAG
  on:
    condition: '"${TRAVIS_SCALA_VERSION}" == "2.12.8" && "${TRAVIS_JDK_VERSION}" == "oraclejdk8"'
    tags: true
after_success:
  - bash <(curl -s https://codecov.io/bash)
